### PR TITLE
Update README.md to include Google's OnHub Recovery Utility

### PR DESCRIPTION
**Pull request by magic-madrigal**
Adding a note to Google's Galeforce supported Recovery USB Utility

### CODE REVIEW

**Comment by idvoretskyi** [comment]
LGTM

**Comment by idvoretskyi** [comment]
The recovery tool officially supports only OnHub devices.

Does Galeforce support them? https://github.com/marcosscriven/galeforce/issues/16

**Comment by magic-madrigal** [comment]
The recovery tool allows you to use your own local image. I recently used this tool to flash my Google Wifi device without any issues.

**Comment by idvoretskyi** [comment]
@magic-madrigal thanks.

PR looks good to me.

**Comment by idvoretskyi** [comment]
@marcosscriven anything that blocks this PR from merging?

**Comment by magic-madrigal** [comment]
I don't have the ability to merge the PR.

**Comment by idvoretskyi** [comment]
@magic-madrigal it was a request to @marcosscriven, the repo owner.

**Comment by hongkongkiwi** [comment]
Seems he has given up on this project, hope we can find another person to handle PR and ongoing development.

**Pull request closed without merging**
